// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myapp.Data;

#nullable disable

namespace myapp.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260222193252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("myapp.Data.Entities.BuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Galaxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingType", "Galaxy", "System", "Position")
                        .IsUnique();

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("myapp.Data.Entities.BuildingQueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BuildingQueue");
                });

            modelBuilder.Entity("myapp.Data.Entities.DefenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Galaxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DefenseType", "Galaxy", "System", "Position")
                        .IsUnique();

                    b.ToTable("Defenses");
                });

            modelBuilder.Entity("myapp.Data.Entities.DefenseQueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DefenseQueue");
                });

            modelBuilder.Entity("myapp.Data.Entities.EnemyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ColonyCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Crystal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefensesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Deuterium")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmpireId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExploredGalaxiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Galaxy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHomeworld")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KnownEnemyCoordinatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastResourceUpdate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Metal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpiedEnemyPowerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("System")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnologiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Galaxy", "System", "Position")
                        .IsUnique();

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("myapp.Data.Entities.FleetMissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("CargoCrystal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CargoDeuterium")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CargoMetal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FuelConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetGalaxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSystem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FleetMissions");
                });

            modelBuilder.Entity("myapp.Data.Entities.FleetMissionShipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FleetMissionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FleetMissionId");

                    b.ToTable("FleetMissionShips");
                });

            modelBuilder.Entity("myapp.Data.Entities.GameMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("myapp.Data.Entities.GameState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Crystal")
                        .HasColumnType("REAL");

                    b.Property<double>("DarkMatter")
                        .HasColumnType("REAL");

                    b.Property<double>("Deuterium")
                        .HasColumnType("REAL");

                    b.Property<bool>("DevModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeGalaxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastResourceUpdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSavedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Metal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("GameState");
                });

            modelBuilder.Entity("myapp.Data.Entities.PlanetState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Crystal")
                        .HasColumnType("REAL");

                    b.Property<double>("Deuterium")
                        .HasColumnType("REAL");

                    b.Property<long>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Galaxy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastResourceUpdate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Metal")
                        .HasColumnType("REAL");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Galaxy", "System", "Position")
                        .IsUnique();

                    b.ToTable("PlanetStates");
                });

            modelBuilder.Entity("myapp.Data.Entities.PlayerPlanetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Galaxy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHomeworld")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Galaxy", "System", "Position")
                        .IsUnique();

                    b.ToTable("PlayerPlanets");
                });

            modelBuilder.Entity("myapp.Data.Entities.ResearchQueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResearchQueue");
                });

            modelBuilder.Entity("myapp.Data.Entities.ShipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Galaxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("System")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipType", "Galaxy", "System", "Position")
                        .IsUnique();

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("myapp.Data.Entities.ShipyardQueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShipyardQueue");
                });

            modelBuilder.Entity("myapp.Data.Entities.TechnologyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnologyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyType")
                        .IsUnique();

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("myapp.Data.Entities.FleetMissionShipEntity", b =>
                {
                    b.HasOne("myapp.Data.Entities.FleetMissionEntity", "FleetMission")
                        .WithMany()
                        .HasForeignKey("FleetMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FleetMission");
                });
#pragma warning restore 612, 618
        }
    }
}
